### ISSUE TITLE
p.145 Setが内包するMapにputする値はObjectのインスタンスである場合がある

### ISSUE THREAD

**Issue by dai0304** [acroquest/javabook-support#16]
本文中では `boolean` とあり、#3 にて `Boolean` と指摘されています。

しかし、私が手元で確認した実装 (jdk-8u131-macosx-x64) では下記のように`Object`型の定数フィールドを作り、addの際はこの値をMapにputしているようでした。

```
// Dummy value to associate with an Object in the backing Map
private static final Object PRESENT = new Object();
...
public boolean add(E e) {
  return m.put(e, PRESENT)==null;
}
```

このあたりは仕様で規定されたものではなく、バージョン等々によって実装が異なる可能性があるため、言及するにしても上手に言及したいところだと思います。

**Comment by phonypianist** [comment]
ご指摘ありがとうございます。
最新のupdate 131に合わせた上で、表現を直して正誤表に反映しました。
