### ISSUE TITLE
p.239 inputStream がリソースリークする可能性がある

### ISSUE THREAD

**Issue by dai0304** [acroquest/javabook-support#17]
L4で `new FileInputStream` を実行した時点でファイルはopenしているはずです。
L5で行う `new FileOutputStream` で例外が発生した場合、finally blockでclose処理を行う対象は`FileChannel` に限定されており、L4の`FileInputStream`はcloseされません。

**Comment by phonypianist** [comment]
ご指摘ありがとうございます。
`new FileOutputStream` を行う前に `inputStream.getChannel()` するように、正誤表に記載いたしました。
