### ISSUE TITLE
p.352 TopPage クラスのソースコードが明示されていない

### ISSUE THREAD

**Issue by dai0304** [acroquest/javabook-support#19]
TopPageBuilder.java 内で `TopPage` （恐らく `extends Page`）クラスを利用していますが、そのコードの記載がありません。

**Comment by takuyao** [comment]
ご指摘ありがとうございます。
TopPageクラスのコードは、以下の通りです。

■TopPage.java
```
public class TopPage extends Page {
	// 内容はPageと同じ。
}
```

**Comment by takuyao** [comment]
正誤表にも反映いたしました。
