### ISSUE TITLE
p.236 「書き込み」のサンプル内におけるコメントtypo

### ISSUE THREAD

**Issue by dai0304** [acroquest/javabook-support#20]
typo

誤: `(4) ファイルの読み込みに失敗した場合`
正: `(4) ファイルの書き込みに失敗した場合`

あと細かいかもしれませんが、(3) についても「書き込みにおいてファイルが存在しないことがなぜエラーになるのか」と違和感を感じます。

**Comment by takuyao** [comment]
ご指摘ありがとうございます。

Typoを修正した上で、コメントいただいた通り、書き込みの場合ファイルが存在しなくてもエラーとならないため、合わせてコードを修正いたしました。

正誤表に反映しました。
