### ISSUE TITLE
p.379 pom.xmlサンプルの url 要素が例として不適切

### ISSUE THREAD

**Issue by dai0304** [acroquest/javabook-support#21]
pom.xml の `<url>` 要素は、Project information の項目ですので、mavenのURLではなく、この例で言う `javabook-maven-example` が属するプロジェクトのURLを示すべきです。

https://maven.apache.org/pom.html#More_Project_Information

**Comment by phonypianist** [comment]
ご指摘ありがとうございます。
<url>はhttps://github.com/acroquest/javabook-maven-exampleを示すよう、正誤表に反映しました。
