### ISSUE TITLE
p.78 StaticTestMain.javaの結果に一部誤りがある

### ISSUE THREAD

**Issue by kuni02** [acroquest/javabook-support#26]
p.78 StaticTestMain.javaの最後に書かれている「System.out.println(test.instanceMethod())」の結果が「Hi Murata yay!」となっていますが、その前の「test2.staticField = "Okada";」でstaticFieldの値を「Okada」にしているため、「Hi Okada yay!」が正しいです。（実行して検証済み）

**Comment by muraken720** [comment]
ご指摘ありがとうございます。正誤表に反映しました。
