### ISSUE TITLE
p.129 String型のelementにObject型を代入している

### ISSUE THREAD

**Issue by kuni02** [acroquest/javabook-support#27]
p.129の中央のサンプルコード7行目「String element = iterator.next();」部分
Iteratorのnextメソッドの戻り値はObject型なので、
String型のelementに代入する場合は、String型に型変換する必要があると思います。

以下で実行できました。
String element = (String)iterator.next();

**Comment by dai0304** [comment]
補足します。

L7で`next()` の戻り値を`String`にキャストするのではなく、
L6で`element`の型を`Iterator<String>`にすべきところかと思います。

**Comment by phonypianist** [comment]
kuni02様、dai0304様、ご指摘ありがとうございます。
dai0304様が記載されている通り、iteratorの型を総称型で記述するよう、正誤表に反映しました。
