### ISSUE TITLE
P.90: Employee.javaにtypo

### ISSUE THREAD

**Issue by tyokinuhata** [acroquest/javabook-support#29]
P.90 サンプルコード「Employee.java」にtypo

２行目
誤: `private int employeNo;`
正: `private int employeeNo;`

11行目
誤: `result = prime * result + employeNo;`
正: `result = prime * result + employeeNo;`

なお, コード自体は正常に動作します.

**Comment by phonypianist** [comment]
ご指摘ありがとうございます。
正誤表に反映しました。
