### ISSUE TITLE
p.145: booleanではなく、Boolean

### ISSUE THREAD

**Issue by YoshikiShibata** [acroquest/javabook-support#3]
p.145のNote 「MapとSetの関係」の説明で最後の行の「boolean」は、「Boolean」が正しい。

**Comment by muraken720** [comment]
ご指摘ありがとうございます。

誤：
　通常は boolean 型で「TRUE」が格納されます。この boolean 値は、使用されることはありません。

正：
　通常は Boolean 型で「TRUE」が格納されます。この Boolean 値は、使用されることはありません。

として正誤表に記載しました。
