### ISSUE TITLE
P116: Noteにtypo

### ISSUE THREAD

**Issue by tyokinuhata** [acroquest/javabook-support#30]
１行目
誤: `class Student implements Comparable<Student>`
正: `class Student2 implements Comparable<Student>`

**Comment by phonypianist** [comment]
ご指摘ありがとうございます。
前後の説明文をStudentとしており、「もしStudentクラスをComparableにしたら」という仮定で書き直している意図がありますので、Student2ではなくStudentの方に揃え、正誤表に反映しました。。
