### ISSUE TITLE
p.164のmapメソッドのみを使った場合

### ISSUE THREAD

**Issue by KiyoshimaHideto** [acroquest/javabook-support#36]
本文中では、mapメソッドが使われず、forEachだけ使われていて例として不適切。
mapメソッドを使った場合は、以下のようになるのではないか？

    List<Student> allStudents = new ArrayList<>();
    groups.stream()
      .map(g -> g.getStudents().stream())
      .forEach(streamStudent -> streamStudent.forEach(student -> allStudents.add(student)));

    allStudents.stream()
    .sorted((s1,s2) -> s2.getScore() - s1.getScore())
    .forEach(s -> System.out.println(s.getName() + " " + s.getScore()));

以上、宜しくお願い致します。

**Comment by phonypianist** [comment]
ご指摘ありがとうございます。
確かに、mapメソッドを使った場合は記述していただいたようになりますが、複雑になりすぎるため、「flatMapメソッドを使わない場合」として、正誤表に反映しました。
