### ISSUE TITLE
13−6−4 Jenkinsの選択項目にtypo

### ISSUE THREAD

**Issue by yasugahira0810** [acroquest/javabook-support#38]
「13-6-4 Jenkinsでレポートを作成する」のビルド後の処理の選択項目が実機と以下のとおり異なっていました。

**誤**

- Checkstyle警告の修正
- FindBugs警告の修正

**正**

- Checkstyle警告の集計
- FindBugs警告の集計

Jenkins ver. 2.60.3で実機確認した際のキャプチャを添付します。
ご確認のほどよろしくお願いします。

![2017-11-23 21 57 32](https://user-images.githubusercontent.com/3108577/33174143-19ece588-d09a-11e7-9307-b99249e67d23.png)

**Comment by phonypianist** [comment]
ご指摘ありがとうございます。
正誤表に反映しました。
