### ISSUE TITLE
p.179 「メソッドのシグネチャ（宣言の内容）でthrows節を記述」

### ISSUE THREAD

**Issue by munierujp** [acroquest/javabook-support#39]
p.179に **「メソッドのシグネチャ（宣言の内容）でthrows節を記述」** とありますが、throws節はシグネチャには含まないのではないでしょうか。

https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.4.2

**Comment by phonypianist** [comment]
ご指摘ありがとうございます。
ご指摘の通り、throws節はシグネチャではありませんので、修正を正誤表に反映しました。
