### ISSUE TITLE
第二刷 pp.45 誤字

### ISSUE THREAD

**Issue by toyo** [acroquest/javabook-support#43]
第二刷に対する誤字の指摘です。

2-2-1 三段落目冒頭
「クラスは、classブロック内に、保持させるを変数を宣言して作ります」は、
「クラスは、classブロック内に、保持させる変数を宣言して作ります」の誤字ではないでしょうか。

もう少し正確に書くと、
「クラスは、classブロック内に、保持させる変数とメソッドを宣言して作ります」
となる気がしますが、2-2-2項の記述との関連で、判断が必要と思います。

**Comment by phonypianist** [comment]
ご指摘ありがとうございます。
2-2-1は変数のみの説明にとどめたいため、前者の内容で正誤表に反映させていただきました。
