### ISSUE TITLE
第二刷 pp.181 色の一貫性なし

### ISSUE THREAD

**Issue by toyo** [acroquest/javabook-support#45]
pp.181-182の二つの「構文」について、背景が灰色となっていますが、他の部分では背景がピンクであり、一貫性がありません。
また、「○」付き表記の有無について、他の部分では、特筆すべきところ以外は付加されていませんので、ここでも「○構文」は不要ではと思います。

**Comment by phonypianist** [comment]
ご指摘ありがとうございます。
他のコード記載と扱いは同じですが、表現が異なっている旨、正誤表に反映しました。
