### ISSUE TITLE
第二刷 pp.278 サンプルプログラムからException.

### ISSUE THREAD

**Issue by toyo** [acroquest/javabook-support#46]
pp.278の最終行のプログラムをJRE1.8.0 162で動かすと、下記の通りRuntimeExceptionが発生します。
例で用いる値を変えるべきと思います。

Exception in thread "main" java.time.DateTimeException: Invalid value for SecondOfMinute (valid values 0 - 59): 67
	at java.time.temporal.ValueRange.checkValidValue
	at java.time.temporal.ChronoField.checkValidValue
	at java.time.LocalTime.of
	at java.time.LocalDateTime.of
	at main.main

**Comment by phonypianist** [comment]
ご指摘ありがとうございます。
あり得ない秒になっていたため、適切な数値に修正しました。
