### ISSUE TITLE
8-4-3XML (1)DOM  Node のgetNextSibling() は 閉じタグも返す ?

### ISSUE THREAD

**Issue by devDeny** [acroquest/javabook-support#48]
初版第2刷を読ませていただきました。Nodeクラスの仕様だと思いますが。閉じタグも nextSibling として return されているものと思います。
p.255
出力結果には 「#text=」のあとに空行が続くものが出力されていますが、これはXMLファイル
中でタグとタグの間の改行空白も要素として読み込まれているためです。

空行などがテキストノードとして読みこまれるのは確かだと思いますが、囲む親のノードの閉じタグも
検出されてしまう点も、ご説明いただけるとよかったなと思います。じぶんは、開くタグから閉じタグまでで
ひとつのノードだと思っているもので、このクラスの仕様がどうも、しっくりいきません。

**Comment by devDeny** [comment]
すみません　調べ方が甘かったみたいです
> 囲む親のノードの閉じタグも
タグではないようです。
node.getChildNodes().getLength()　などで分岐し、閉じタグ以降の改行や空白は表示しない
サンプルがよいと思います。さらに 先祖ノードをスタックに積んでおいて、表示するとき
ノードの親子関係が明確になると、さらに使いやすいかと、期待いたします。

**Comment by phonypianist** [comment]
コメントありがとうございます。

タグの後ろもTextNodeあることを、p.253の図「staff.xmlをツリー構造で表すと」で表現したつもりでしたが、説明不足ですね。
ご指摘の通り、p.254～255のコード例と出力例のところで、インデントやタグの対応付けを出力するようにしておけば、分かりやすかったと思います。

改善指摘として扱わせていただきます。
