### ISSUE TITLE
p.63: booleanのサイズ

### ISSUE THREAD

**Issue by YoshikiShibata** [acroquest/javabook-support#5]
p.63の「3-1-2 プリミティブ型」のboolean型のサイズが1bitと記述されているが、言語仕様でも1ビットとは定義されていない。言語仕様の「4.2 Primitive Types and Values」で、次のように表現されているだけです。

The boolean type has exactly two values: true and false.

サイズとして`1bit`と表記するのは不適切だと思います。

**Comment by muraken720** [comment]
ご指摘ありがとうございます。

p.63 表「プリミティブ型」のboolean型のサイズの部分について、「1bit」ではなく、「-」とするように正誤表に記載しました。
