### ISSUE TITLE
第二刷 pp.172 誤記?

### ISSUE THREAD

**Issue by toyo** [acroquest/javabook-support#50]
5-5-3章の表「Listで全要素に関数を適用するメソッド」の引数列の記載について。

「引数がStream対象のオブジェクト」という二つの文章について、いずれも
「引数がList対象のオブジェクト」の誤記ではないでしょうか。

**Comment by phonypianist** [comment]
ご指摘ありがとうございます。
ご指摘の通り、removeIfとreplaceAllはStreamではなく、内部でIteratorもしくは配列（実装クラスにより異なる）ため、「List」への修正として正誤表に反映しました。
