### ISSUE TITLE
p153: 配列でforEachを使用

### ISSUE THREAD

**Issue by rmswimkktt** [acroquest/javabook-support#7]
`students`は配列なので`forEach`を使用する際は
`Array.stream(students)`で`Stream`に変換する必要があるかと思います。

**Comment by phonypianist** [comment]
ご指摘ありがとうございます。

誤：
　students.forEach(s ->
　　System.out.println(s.getName() + ":" + s.getScore()));

正：
　Arrays.stream(students).forEach(s ->
　　System.out.println(s.getName() + ":" + s.getScore()));

で正誤表に記載いたしました。
